### ISSUE TITLE
Unable to uninstall Add-On

### ISSUE THREAD

**Issue by BertrumUK** [qJake/hassio-addon-repository#2]
I have tried to uninstall this add-on on 2 different Rpi's and both are unable to be removed. Container was deleted via Portainer but it still persists even after a restart of Hassio.

**Comment by BertrumUK** [comment]
Here are the Hass.io system logs showing the issue 

19-09-08 07:20:56 INFO (SyncWorker_17) [hassio.docker.interface] Stop addon_ac23ff49_hacc application
19-09-08 07:21:06 INFO (SyncWorker_17) [hassio.docker.interface] Clean addon_ac23ff49_hacc application
19-09-08 07:21:11 INFO (SyncWorker_10) [hassio.docker.interface] Remove image qjake/hacc-hassio-armv7 with latest and 
19-09-08 07:21:11 WARNING (SyncWorker_10) [hassio.docker.interface] Can't remove image qjake/hacc-hassio-armv7: 400 Client Error: Bad Request ("invalid reference format")

**Comment by qJake** [comment]
@BertrumUK Unfortunately there is no custom code of mine that executes when the Hass.io addon is uninstalled, and [in the dev docs](https://developers.home-assistant.io/docs/en/hassio_addon_repository.html) there is no special instruction for handling an uninstall. So, I don't believe this is something specific to HACC, but more likely specific to your setup of Home Assistant.

I think you should open this issue with the Home Assistant team, but I'm not quite sure which repo to use, possibly one of these:

* https://github.com/home-assistant/hassio-addons
* https://github.com/home-assistant/home-assistant

**Comment by BertrumUK** [comment]
I am running Hassio on 2 Rpi's, 1 is running standard Hassio and the other is running Raspian with a docker install of Hassio. It seems strange that both instances have the same issue.

Are you able to uninstall the add-on yourself ?

I will raise an issue though on https://github.com/home-assistant/hassio-addons

**Comment by qJake** [comment]
Hmm, strangely enough I was able to uninstall it in prior versions but with 0.5.0 I'm actually getting the same error.

I found this which leads me to believe that one of the image names is possibly getting screwed up?

https://stackoverflow.com/a/52818152

Not sure, going to research some more.

**Comment by qJake** [comment]
I filed a bug for this, we'll see what they say: https://github.com/home-assistant/hassio/issues/1280

**Comment by kalyway101** [comment]
Oddly enough, these many months later, I am running into this issue with not being able to uninstall. HACS 1.2.2 and Hassio 4.11. HA 0.112.4

**Comment by qJake** [comment]
@kalyway101 This is the repository for Home Assistant **Command Center** (HACC), not HACS (the store). Please go to https://hacs.xyz/ and find the links to submit an issue for that project.

As for this bug, it was fixed in v1.x and will be released accordingly.
